### ISSUE TITLE
Feature idea: automatically send list to Chat

### ISSUE THREAD

**Issue by ewiner** [LambyPants/google-meet-randomizer#3]
Just an unsolicited suggestion - it could save a few clicks if there were a way to automatically send the list the Meet's chat window.

**Comment by LambyPants** [comment]
@ewiner thanks for the suggestion - perhaps worth adding a fourth button to autopost to the chat window - that's how we use it for our standups, too. May require moving a button or two to icons to save some space.

Should be fairly easy to add; I'll add it to my side project todo list :]

**Comment by LambyPants** [comment]
@ewiner `2.1.0` adds an autopost feature and it should go live this week (takes a while for Chrome to publish); hope that does the trick, thanks for the suggestion.

**Comment by ewiner** [comment]
Thanks!~
